### ISSUE TITLE
question about mount

### ISSUE THREAD

**Issue by mrc4tt** [Hetsh/docker-teamspeak#1]
Hi.

If I want to mount app.ini

Do I need to first: ``docker run --mount type=bind,source=/path/to/app.ini,target=/etc/teamspeak-server/app.ini ...``

Or first: create /etc/teamspeak-server/app.ini (inside docker's container or outside of that?)

**Comment by Hetsh** [comment]
Hi. You need to create an `app.ini` on your host (outside the container) before you mount it.

**Comment by mrc4tt** [comment]
Hi @Hetsh 

Can you explain to me (example output) how I can get the "data" to be saved?

If I example "turn off" server <-> it should have/had saved the data, without its reset (eg if server has been rebooted)

**Comment by Hetsh** [comment]
Ah, now i got your problem. If your only goal is to keep the data after a reboot you don't need a custom app.ini. What you need to do instead is mount the data-volume with `--mount type=bind,source=/path/to/data/on/host,target=/teamspeak-server-data`. To be honest, the steps I put in the ReadMe are not perfect. I will update them later.

**Comment by Hetsh** [comment]
And don't forget to apply the correct permissions. BTW, this is the "Creating persistent storage" step from the ReadMe.
